<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Soflomo\User\Module'      => __DIR__ . '/Module.php',
    'Soflomo\User\Entity\User' => __DIR__ . '/src/Soflomo/User/Entity/User.php',
    'Soflomo\User\Entity\Role' => __DIR__ . '/src/Soflomo/User/Entity/Role.php',
);